In [1]:
import pandas as pd
import numpy as np
import matplotlib as mp
import seaborn as sb
import matplotlib.pyplot as plt
import random

from sklearn.model_selection import train_test_split

# Importing the required packages
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

from sklearn.neighbors import KNeighborsClassifier

In [6]:
df = pd.read_csv('../data/df.csv')
df

aX    aY    aZ    gX    gY    gZ  little  ring  middle  index  thumb  \
0      0.03  0.91  0.40  2.14 -3.23 -0.92     409   458     189    240    199   
1      0.02  0.91  0.40  0.73 -0.79 -1.59     416   455     192    243    195   
2      0.01  0.91  0.41 -1.59 -1.83 -5.62     409   451     190    242    197   
3      0.00  0.89  0.43  3.42 -4.70 -1.10     413   451     190    249    202   
4      0.05  0.91  0.38 -1.46 -1.28 -0.06     410   458     190    243    199   
...     ...   ...   ...   ...   ...   ...     ...   ...     ...    ...    ...   
61983  0.38  0.79  0.47  1.16 -0.73 -2.99     412   397     265    448    358   
61984  0.37  0.81  0.49  9.70 -8.61  9.83     410   397     268    447    360   
61985  0.42  0.79  0.43  3.11 -2.32 -2.20     408   396     267    450    359   
61986  0.42  0.80  0.44  1.65 -3.36 -2.75     410   401     264    454    359   
61987  0.41  0.79  0.44 -1.46 -2.01 -3.85     408   395     267    448    361   

       number  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
61983      29  
61984      29  
61985      29  
61986      29  
61987      29  

[61988 rows x 12 columns]

In [12]:
df.head()

aX    aY    aZ    gX    gY    gZ  little  ring  middle  index  thumb  \
0  0.03  0.91  0.40  2.14 -3.23 -0.92     409   458     189    240    199   
1  0.02  0.91  0.40  0.73 -0.79 -1.59     416   455     192    243    195   
2  0.01  0.91  0.41 -1.59 -1.83 -5.62     409   451     190    242    197   
3  0.00  0.89  0.43  3.42 -4.70 -1.10     413   451     190    249    202   
4  0.05  0.91  0.38 -1.46 -1.28 -0.06     410   458     190    243    199   

   number  
0       0  
1       0  
2       0  
3       0  
4       0

In [33]:
df.loc[4422]

aX          0.93
aY         -0.28
aZ         -0.23
gX          0.12
gY         -2.44
gZ         -2.99
little    225.00
ring      295.00
middle    388.00
index     468.00
thumb     298.00
number      2.00
Name: 4422, dtype: float64

In [37]:
aX = df['aX']
aY = df['aY']
aZ = df['aZ']
gX = df['gX']
gY = df['gY']
gZ = df['gZ']

f1 = df['little']
f2 = df['ring']
f3 = df['middle']
f4 = df['index']
f5 = df['thumb']

hw = [[a,b,c,d,e,f,g,h,i,j,k] for a,b,c,d,e,f,g,h,i,j,k in zip(aX,aY,aZ,gX,gY,gZ,f1,f2,f3,f4,f5)]
hw

[[0.03, 0.91, 0.4, 2.14, -3.23, -0.92, 409, 458, 189, 240, 199],
 [0.02, 0.91, 0.4, 0.73, -0.79, -1.59, 416, 455, 192, 243, 195],
 [0.01, 0.91, 0.41, -1.59, -1.83, -5.62, 409, 451, 190, 242, 197],
 [0.0, 0.89, 0.43, 3.42, -4.7, -1.1, 413, 451, 190, 249, 202],
 [0.05, 0.91, 0.38, -1.46, -1.28, -0.06, 410, 458, 190, 243, 199],
 [0.07, 0.85, 0.41, -12.94, -9.83, 2.38, 413, 454, 192, 241, 189],
 [0.08, 0.92, 0.45, -2.26, -2.99, -7.81, 412, 458, 190, 240, 196],
 [0.1, 0.88, 0.45, -0.31, -3.3, -7.75, 415, 455, 195, 244, 197],
 [0.08, 0.86, 0.46, 1.71, -3.48, -2.62, 413, 452, 184, 239, 198],
 [0.08, 0.91, 0.47, 2.5, -4.58, 1.71, 414, 457, 197, 244, 199],
 [0.09, 0.88, 0.46, 1.4, -2.32, 0.43, 413, 454, 193, 242, 203],
 [0.12, 0.9, 0.46, -0.49, -1.22, -3.72, 409, 452, 195, 247, 195],
 [0.07, 0.9, 0.45, 2.08, -2.44, -3.42, 406, 452, 180, 242, 197],
 [0.1, 0.89, 0.45, 1.71, -2.75, -6.04, 402, 456, 197, 242, 193],
 [0.11, 0.89, 0.45, 4.58, -0.73, -2.75, 405, 455, 187, 237, 195],
 [0.07, 0.89, 0.45

In [41]:
hw_target = [0]*2170 + [1]*2032 + [2]*2014 + [3]* 2112 + [4]*2028 +[5]*2013 +[6]*2037+[7]*2014+[8]*2016+[9]*2049 +[10]*2052 +[11]*2004 + [12]*2041 +[13]*2124+[14]*2021 +[15]*2411 +[16]*2023 +[17]*2067 +[18]*2195 +[19]*2012+[20]*2032+[21]*2039+[22]*2048+[23]*2121+[24]*2100+[25]*2063+[26]*2050+[27]*2046+[28]*2031+[29]*2023

In [46]:
2170 + 2032 + 2014 +  2112 +2028 +2013 +2037+2014+2016+2049 +2052 +2004 +2041 +2124+2021 +2411 +2023 +2067 +2195 +2012+2032+2039+2048+2121+2100+2063+2050+2046+2031+2023

61988

In [42]:
hw_target

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [43]:
kn = KNeighborsClassifier()

In [48]:
kn.fit(hw, hw_target)

KNeighborsClassifier()

In [49]:
kn.score(hw,hw_target)

0.9896431567400142

In [50]:
kn.predict([[0.03,0.91,0.4,2.14,-3.23,-0.92,409,458,189,240,200]])

array([0])

In [53]:
kn.predict([[0.94,-0.3,0.19,-0.31,-2.42,-1,220,258,186,461,320]])

array([22])

In [64]:
hw_target[50384]

24

In [56]:
kn._fit_X

array([[3.00e-02, 9.10e-01, 4.00e-01, ..., 1.89e+02, 2.40e+02, 1.99e+02],
       [2.00e-02, 9.10e-01, 4.00e-01, ..., 1.92e+02, 2.43e+02, 1.95e+02],
       [1.00e-02, 9.10e-01, 4.10e-01, ..., 1.90e+02, 2.42e+02, 1.97e+02],
       ...,
       [4.20e-01, 7.90e-01, 4.30e-01, ..., 2.67e+02, 4.50e+02, 3.59e+02],
       [4.20e-01, 8.00e-01, 4.40e-01, ..., 2.64e+02, 4.54e+02, 3.59e+02],
       [4.10e-01, 7.90e-01, 4.40e-01, ..., 2.67e+02, 4.48e+02, 3.61e+02]])

In [57]:
kn._y

array([ 0,  0,  0, ..., 29, 29, 29])

In [59]:
input_arr = np.array(hw)
target_arr = np.array(hw_target)

In [60]:
# (샘플 수, 특성 수)
input_arr.shape

(61988, 11)

In [61]:
np.random.seed(42)
index = np.arange(61988)
np.random.shuffle(index)

In [62]:
train_input = input_arr[index[:40000]]
train_target = target_arr[index[:40000]]

In [63]:
index

array([50384,   848,  7613, ...,   860, 15795, 56422])

In [68]:
input_arr[50384],train_input[0]

(array([-2.60e-01, -9.30e-01, -2.10e-01,  9.80e-01, -2.62e+00, -2.93e+00,
         4.02e+02,  2.65e+02,  2.03e+02,  4.49e+02,  3.05e+02]),
 array([-2.60e-01, -9.30e-01, -2.10e-01,  9.80e-01, -2.62e+00, -2.93e+00,
         4.02e+02,  2.65e+02,  2.03e+02,  4.49e+02,  3.05e+02]))

In [69]:
test_input = input_arr[index[40000:]]
test_target = target_arr[index[40000:]]

In [70]:
kn = kn.fit(train_input, train_target)

In [71]:
kn.score(test_input, test_target)

0.9846734582499546

In [72]:
kn.predict(test_input)

array([ 7, 13, 15, ...,  0,  7, 27])

In [73]:
test_target

array([ 7, 13, 15, ...,  0,  7, 27])

In [79]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(hw, hw_target,random_state=42)

In [82]:
test_target

[24,
 0,
 3,
 28,
 21,
 22,
 24,
 7,
 4,
 6,
 10,
 28,
 24,
 20,
 11,
 20,
 5,
 11,
 28,
 0,
 10,
 28,
 13,
 29,
 15,
 1,
 0,
 8,
 15,
 15,
 1,
 17,
 17,
 27,
 18,
 6,
 7,
 19,
 17,
 2,
 14,
 13,
 9,
 0,
 13,
 4,
 6,
 27,
 15,
 5,
 15,
 29,
 17,
 26,
 29,
 27,
 11,
 27,
 26,
 14,
 1,
 20,
 4,
 8,
 10,
 8,
 23,
 14,
 24,
 21,
 1,
 1,
 19,
 11,
 25,
 9,
 22,
 17,
 27,
 27,
 3,
 25,
 9,
 23,
 11,
 16,
 15,
 26,
 6,
 25,
 17,
 13,
 15,
 5,
 19,
 7,
 7,
 3,
 27,
 13,
 15,
 24,
 2,
 23,
 10,
 23,
 8,
 7,
 14,
 28,
 25,
 4,
 12,
 3,
 0,
 5,
 5,
 19,
 18,
 4,
 12,
 29,
 19,
 26,
 3,
 17,
 3,
 27,
 3,
 21,
 25,
 8,
 4,
 19,
 2,
 28,
 19,
 28,
 20,
 17,
 14,
 7,
 24,
 0,
 10,
 24,
 5,
 2,
 25,
 5,
 11,
 28,
 10,
 1,
 13,
 23,
 28,
 23,
 25,
 19,
 1,
 14,
 27,
 3,
 9,
 6,
 10,
 2,
 4,
 8,
 0,
 5,
 16,
 17,
 10,
 27,
 24,
 10,
 22,
 23,
 9,
 25,
 7,
 20,
 14,
 1,
 11,
 13,
 6,
 20,
 1,
 21,
 15,
 0,
 20,
 12,
 22,
 0,
 15,
 11,
 14,
 29,
 28,
 1,
 0,
 24,
 29,
 12,
 22,
 12,
 28,
 17,
 3,
 15,
 17

In [83]:
mean = np.mean(train_input, axis =0)
std = np.std(train_input,axis =0)

In [84]:
mean

array([ 3.69702738e-01, -2.77045019e-01,  1.92720957e-01,  3.28464004e-01,
       -2.95931514e+00, -2.57295520e+00,  3.13077198e+02,  3.33058140e+02,
        3.12259061e+02,  4.15547461e+02,  3.21915962e+02])

In [85]:
std

array([ 0.42879585,  0.71425102,  0.24235382,  5.6255219 ,  6.60612672,
        4.9952981 , 82.09936554, 80.14187209, 94.83121696, 75.74661382,
       54.59329797])

In [87]:
train_scaled = (train_input-mean)/std
train_scaled

array([[ 1.23671269,  0.07986691,  0.93779849, ...,  0.92523266,
         0.60006034, -2.1232636 ],
       [ 1.32999717,  0.28987711,  0.73148856, ...,  0.91468761,
        -2.10633126, -1.75691826],
       [ 0.86357474, -0.39615622,  0.69022657, ..., -0.68816011,
         0.57365652,  0.16639474],
       ...,
       [-0.23251797,  1.68994512,  0.31886869, ..., -0.70925021,
        -1.59145676, -1.24403479],
       [-1.1420417 , -0.98418478, -1.2903488 , ..., -0.22417788,
        -0.04683326,  2.51100488],
       [ 1.23671269, -0.07414057,  0.48391663, ...,  0.98850296,
         0.42843551, -0.29153693]])

In [88]:
kn.fit(train_scaled, train_target)

KNeighborsClassifier()

In [89]:
test_scaled = (test_input-mean)/std
test_scaled

array([[-1.4685374 , -0.91418138, -1.66170668, ..., -1.15214235,
         0.44163742, -0.30985419],
       [-0.11591236,  1.67594444,  0.23634471, ..., -0.76197547,
        -1.53864912, -1.26235206],
       [ 1.37663941,  0.10786827,  0.40139266, ...,  1.00959307,
         0.75848327, -1.59206286],
       ...,
       [ 0.1639411 ,  1.47993492,  0.93779849, ..., -0.78306557,
        -1.32741856, -1.6286974 ],
       [ 1.00350147, -0.2001467 , -2.32189847, ..., -1.37358841,
         0.40203169,  0.56937461],
       [ 1.23671269, -0.21414738, -0.3413231 , ...,  1.06231832,
         0.67927181,  0.36788468]])

In [90]:
kn.score(test_scaled, test_target)

0.9696715493321288

In [ ]:
np.random